### ISSUE TITLE
Handling ports in Long URL

### ISSUE THREAD

**Issue by mikeleo** [llonchj/yourls_plugins#1]
Admittedly this is rare case to have public URLs with a port in the Long URL, but it should be handled in case it does exist.  

Change the new_url generation to something like:

```
$new_url = $parsed_url["scheme"]."://".$parsed_url["host"];
if (isset($parsed_url["port"]) && $parsed_url["port"] != "")
   $new_url = $new_url . ":" . $parsed_url["port"];
$new_url = $new_url.$parsed_url["path"];
```

**Comment by llonchj** [comment]
Thanks a lot. Checkout the master
